
# Site settings

# NB! Set your site's url, otherwise stuff will break :)

url: "https://cmtoomey.github.io"

# If you're hosting your site at a Project repository on GitHub pages
# (https://yourusername.github.io/repository-name)
# and NOT your user repository (https://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
#
# NB! Without this *nothing* will work, because it's used in every path :)

# baseurl: /personal-jekyll-theme

# Google tracking id to track your visitors

google-tracking-id: "UA-71148817-1"

# Forces https everywhere in your website, except when you serve it locally
# If you are not hosted on Github Pages, and your host doesn't support https
# then you should disable it

force-https: True

#############
# HTML Head #
#############

lang: "en"
author: "Chris Toomey"
title: "{ Tableauing Dangerously }"
description: "Tableau-centric blog on building all the awesome things, code or no-code"
keywords: "chris, toomey, tableau, alteryx, d3, analysis, awesome"
favicon: "/img/favicon.ico"
errorimg: "/img/utini.gif"

################
# Header layout #
################

background-img: "../img/intro-bg.jpg"

##############################
# Dynamic Text on the Header #
##############################

dynamic-typing: True
shuffle: False # Shuffle the lines.
loop: True
loop-count: False # Set False for infinite loop, or set any number for finite loop.
type-speed: 10
start-delay: 2500
delete-delay: 3000
lines: # You can add HTML Tags in the Text
  - text: "Learn enough to be dangerous"
  - text: "Then build something awesome"

me-img: "/img/helmet.jpg"

################
# Web app mode #
################

web-app-mode: True

# Icons for Web App mode

icon-36p: "/img/web-app/helmet-36p.png"
icon-48p: "/img/web-app/helmet-48p.png"
icon-72p: "/img/web-app/helmet-72p.png"
icon-96p: "/img/web-app/helmet-96p.png"
icon-144p: "/img/web-app/helmet-144p.png"
icon-192p: "/img/web-app/helmet-192p.png"

########
# Blog #
########

post-preview-words: 60

paginate: 5

email-share: True
fb-share: True
twitter-share: True
linkedin-share: True
reddit-share: True
google-plus-share: True
tumblr-share: True
#pinterest-share: True
#pocket-share: True
#vkontakte-share: True

disqus-shortname: "cmtoomey"

syntax-highlight: True

############
# Timeline #
############

events:
  - image: "/img/timeline/mapbox.png"
    date: "November 2017 - Present"
    description: "Work at Mapbox"
  - image: "/img/timeline/zillowimg.png"
    date: "March 2104 - November 2017"
    description: "Work at Zillow"
  - image: "/img/timeline/slalom.png"
    date: "March 2104 - April 2016"
    description: "Worked at Slalom"
  - image: "/img/timeline/married.jpg"
    date: "July 2010"
    description: "Married the woman of my dreams"
  - image: "/img/timeline/pnnl.png"
    date: "June 2008 - February 2014"
    description: "Worked for Pacific Northwest National Laboratory"
  - image: "/img/timeline/lse.png"
    date: "September 2008 - August 2009"
    description: "Graduate School at London School of Economics"
  - image: "/img/timeline/default.jpg"
    date: "September 2004 - August 2008"
    description: "Attended University of Washington"

# First image of the Timeline

timeline-img: "/img/timeline/bomber.jpg"

###########
# Contact #
###########

email: "chris.toomey@mapbox.com"

##################
# Social Buttons #
##################

social:
  - title: "twitter"
    url: "https://twitter.com/Sock1tToomey"
  - title: "github"
    url: "https://github.com/cmtoomey"
  - title: "rss"
    url: "/feed.xml"

############
# 404 page #
############

404-img: "/img/utini.gif"

################################################################################

# NB! Tread carefully if you want to change the variables below this point!

# Sections shown in the index page

pages_list:
  About: 'about'
  Blog: 'latest-post'
  Timeline: 'timeline'
  Contact: 'contact'

# Exclusion list from the generated _site

exclude: ["LICENSE", "README.md", "CONTRIBUTING", "CONTRIBUTORS", "scripts"]

# Pagination path

paginate_path: "blog/page:num/"

# Enable minification SASS

sass:
  style: compressed

gems:
  - jekyll-paginate
